name = "App-ansifold"
badges = [ 'github-actions/test', 'metacpan' ]
authority = "cpan:UTASHIRO"

module_maker = "ModuleBuildTiny"

readme_from = "script/ansifold"
abstract_from = "script/ansifold"
authors_from = "script/ansifold"

[unsupported]
os = [
    "MSWin32",
]
