name = "App-ansifold"
# badges = ["travis"]
badges = ['github-actions/test']
authority="cpan:UTASHIRO"

module_maker="ModuleBuildTiny"

readme_from="script/ansifold"
abstract_from="script/ansifold"
authors_from="script/ansifold"
