name = "App-ansifold"
badges = [ 'github-actions/test', 'metacpan' ]
authority = "cpan:UTASHIRO"
script_files = [ 'script/ansifold', 'script/ansicolrm', 'script/ansicut' ]

module_maker = "ModuleBuildTiny"

readme_from   = "script/ansifold"
abstract_from = "script/ansifold"
authors_from  = "script/ansifold"

[release]
branch = "master"

[unsupported]
os = [
    "MSWin32",
]
